import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
const publicDir = path.resolve(rootDir, "public");

function getCommitHash() {
  if (process.env.GITHUB_SHA) {
    return process.env.GITHUB_SHA.substring(0, 7);
  }
  try {
    return execSync("git rev-parse --short HEAD", { cwd: rootDir, encoding: "utf-8" }).trim();
  } catch {
    return "";
  }
}

const commitHash = getCommitHash();
const buildTimestamp = Date.now();
const buildIso = new Date(buildTimestamp).toISOString();
const buildVersion = commitHash ? `${commitHash}-${buildTimestamp}` : `${buildTimestamp}`;
const cacheName = `upcoin-pwa-${buildVersion}`;

// 1. Generate version.json
const versionData = {
  version: buildVersion,
  commit: commitHash || "unknown",
  buildTime: buildIso,
  timestamp: buildTimestamp,
};

fs.writeFileSync(
  path.join(publicDir, "version.json"),
  JSON.stringify(versionData, null, 2) + "\n",
  "utf-8"
);
console.log(`[PWA] Generated public/version.json (Version: ${buildVersion})`);

// 2. Generate service-worker.js
const swContent = `// Auto-generated by scripts/generate-sw.js on ${buildIso}
// Build Version: ${buildVersion}
// Commit: ${commitHash || "local"}

const CACHE_NAME = "${cacheName}";
const BUILD_VERSION = "${buildVersion}";
const basePath = self.location.pathname.replace(/\\/service-worker\\.js$/, "");

const APP_SHELL = [
  \`\${basePath}/\`,
  \`\${basePath}/manifest.webmanifest\`,
  \`\${basePath}/version.json\`,
  \`\${basePath}/pwa-192x192.png\`,
  \`\${basePath}/pwa-512x512.png\`,
  \`\${basePath}/pwa-512x512-maskable.png\`,
  \`\${basePath}/apple-touch-icon.png\`,
  \`\${basePath}/favicon.png\`,
  \`\${basePath}/logo.png\`,
  \`\${basePath}/og.png\`,
];

function cacheResponse(request, response) {
  if (!response || !response.ok || response.type === "opaque") return response;

  const responseCopy = response.clone();
  void caches.open(CACHE_NAME)
    .then((cache) => cache.put(request, responseCopy))
    .catch(() => undefined);

  return response;
}

// 1. INSTALL
self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => Promise.all(APP_SHELL.map((asset) => cache.add(asset).catch(() => undefined))))
      .then(() => self.skipWaiting())
  );
});

// 2. ACTIVATE
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((cacheNames) => Promise.all(
        cacheNames
          .filter((cacheName) => cacheName.startsWith("upcoin-pwa-") && cacheName !== CACHE_NAME)
          .map((cacheName) => {
            console.log("[PWA SW] Deleting old cache:", cacheName);
            return caches.delete(cacheName);
          })
      ))
      .then(() => self.clients.claim())
      .then(async () => {
        const clients = await self.clients.matchAll({ type: "window" });
        for (const client of clients) {
          client.postMessage({
            type: "SW_ACTIVATED",
            version: BUILD_VERSION,
            cacheName: CACHE_NAME,
          });
        }
      })
  );
});

// 3. FETCH
self.addEventListener("fetch", (event) => {
  const requestUrl = new URL(event.request.url);

  // Ignore non-GET or cross-origin requests
  if (event.request.method !== "GET" || requestUrl.origin !== self.location.origin) return;

  // Never cache payment processing routes or dynamic API endpoints
  if (
    requestUrl.pathname.startsWith(\`\${basePath}/payment/\`) ||
    requestUrl.pathname.startsWith(\`\${basePath}/api/\`)
  ) {
    return;
  }

  // version.json must ALWAYS be network-first (no-cache)
  if (requestUrl.pathname.endsWith("/version.json")) {
    event.respondWith(
      fetch(event.request, { cache: "no-store" }).catch(() => caches.match(event.request))
    );
    return;
  }

  // HTML Navigation: Network-First with Cache fallback
  if (event.request.mode === "navigate") {
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          if (response && response.ok) {
            cacheResponse(event.request, response);
          }
          return response;
        })
        .catch(async () => {
          const cachedPage = await caches.match(event.request);
          const appShell = await caches.match(\`\${basePath}/\`);
          return cachedPage || appShell || Response.error();
        })
    );
    return;
  }

  // Static Assets (scripts, styles, images, fonts, icons)
  const cacheableDestinations = new Set(["font", "image", "manifest", "script", "style"]);
  if (cacheableDestinations.has(event.request.destination)) {
    event.respondWith(
      caches.match(event.request).then((cachedResponse) => {
        const fetchPromise = fetch(event.request)
          .then((networkResponse) => {
            if (networkResponse && networkResponse.ok) {
              cacheResponse(event.request, networkResponse);
            }
            return networkResponse;
          })
          .catch(() => cachedResponse || Response.error());

        return cachedResponse || fetchPromise;
      })
    );
    return;
  }
});

// 4. MESSAGE
self.addEventListener("message", (event) => {
  if (!event.data) return;

  if (event.data.action === "skipWaiting" || event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }

  if (event.data.type === "GET_VERSION") {
    event.ports?.[0]?.postMessage({
      version: BUILD_VERSION,
      cacheName: CACHE_NAME,
    });
  }
});
`;

fs.writeFileSync(path.join(publicDir, "service-worker.js"), swContent, "utf-8");
console.log(`[PWA] Generated public/service-worker.js (Cache: ${cacheName})`);
